/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-10-24 04:20:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.net.URL;
import java.util.Properties;
import java.util.HashMap;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1683697746000L));
    _jspx_dependants.put("jar:file:/Users/jeongmingyeong/CNU/CN_23/apache-tomcat-9.0.82/webapps/ROOT/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.slf4j.Logger");
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("org.slf4j.LoggerFactory");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Roboto\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: Arial, Helvetica, sans-serif;\n");
      out.write("	display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Full-width input fields */\n");
      out.write("input[type=text], input[type=password] {\n");
      out.write("  width: 100%;\n");
      out.write("  padding: 12px 20px;\n");
      out.write("  margin: 8px 0;\n");
      out.write("  display: inline-block;\n");
      out.write("  border: 1px solid #ccc;\n");
      out.write("  box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Set a style for all buttons */\n");
      out.write("button {\n");
      out.write("  background-color: #04AA6D;\n");
      out.write("  color: white;\n");
      out.write("  padding: 14px 20px;\n");
      out.write("  margin: 8px 0;\n");
      out.write("  border: none;\n");
      out.write("  cursor: pointer;\n");
      out.write("  width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button:hover {\n");
      out.write("  opacity: 0.8;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Extra styles for the cancel button */\n");
      out.write(".cancelbtn {\n");
      out.write("  width: auto;\n");
      out.write("  padding: 10px 18px;\n");
      out.write("  background-color: #f44336;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Center the image and position the close button */\n");
      out.write(".imgcontainer {\n");
      out.write("  text-align: center;\n");
      out.write("  margin: 24px 0 12px 0;\n");
      out.write("  position: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("img.avatar {\n");
      out.write("  width: 40%;\n");
      out.write("  border-radius: 10%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("  padding: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("span.psw {\n");
      out.write("  float: right;\n");
      out.write("  padding-top: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* The Modal (background) */\n");
      out.write(".modal {\n");
      out.write("  display: none; /* Hidden by default */\n");
      out.write("  position: fixed; /* Stay in place */\n");
      out.write("  z-index: 1; /* Sit on top */\n");
      out.write("  left: 0;\n");
      out.write("  top: 0;\n");
      out.write("  width: 100%; /* Full width */\n");
      out.write("  height: 100%; /* Full height */\n");
      out.write("  overflow: auto; /* Enable scroll if needed */\n");
      out.write("  background-color: rgb(0,0,0); /* Fallback color */\n");
      out.write("  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */\n");
      out.write("  padding-top: 60px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Modal Content/Box */\n");
      out.write(".modal-content {\n");
      out.write("  background-color: #fefefe;\n");
      out.write("  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */\n");
      out.write("  border: 1px solid #888;\n");
      out.write("  width: 80%; /* Could be more or less, depending on screen size */\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* The Close Button (x) */\n");
      out.write(".close {\n");
      out.write("  position: absolute;\n");
      out.write("  right: 25px;\n");
      out.write("  top: 0;\n");
      out.write("  color: #000;\n");
      out.write("  font-size: 35px;\n");
      out.write("  font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".close:hover,\n");
      out.write(".close:focus {\n");
      out.write("  color: red;\n");
      out.write("  cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Add Zoom Animation */\n");
      out.write(".animate {\n");
      out.write("  -webkit-animation: animatezoom 0.6s;\n");
      out.write("  animation: animatezoom 0.6s\n");
      out.write("}\n");
      out.write("\n");
      out.write("@-webkit-keyframes animatezoom {\n");
      out.write("  from {-webkit-transform: scale(0)} \n");
      out.write("  to {-webkit-transform: scale(1)}\n");
      out.write("}\n");
      out.write("  \n");
      out.write("@keyframes animatezoom {\n");
      out.write("  from {transform: scale(0)} \n");
      out.write("  to {transform: scale(1)}\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Change styles for span and cancel button on extra small screens */\n");
      out.write("@media screen and (max-width: 300px) {\n");
      out.write("  span.psw {\n");
      out.write("     display: block;\n");
      out.write("     float: none;\n");
      out.write("  }\n");
      out.write("  .cancelbtn {\n");
      out.write("     width: 100%;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".closebtn {\n");
      out.write("  margin-left: 15px;\n");
      out.write("  color: white;\n");
      out.write("  font-weight: bold;\n");
      out.write("  float: right;\n");
      out.write("  font-size: 22px;\n");
      out.write("  line-height: 20px;\n");
      out.write("  cursor: pointer;\n");
      out.write("  transition: 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".closebtn:hover {\n");
      out.write("  color: black;\n");
      out.write("}\n");
      out.write(".countDown{\n");
      out.write("  text-align: center;\n");
      out.write("  font-size: 60px;\n");
      out.write("  margin-top: 0px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var loginUser ='';\n");
      out.write("function login(){	\n");
      out.write("	\n");
      out.write("	var hakbun ='';\n");
      out.write("	var srcFlag = true;\n");
      out.write("	if($(\"#hakbun\").val() !=\"\") {\n");
      out.write("		$(\"#alertDiv\").hide();\n");
      out.write("		hakbun = $(\"#hakbun\").val();\n");
      out.write("		console.log(\"입력하신 학번은-->\"+hakbun);\n");
      out.write("		srcFlag=true;\n");
      out.write("	}else{\n");
      out.write("		$(\"#alertDiv\").show();\n");
      out.write("		srcFlag=false;\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("		\n");
      out.write("	if(srcFlag){	\n");
      out.write("		param = {\n");
      out.write("				HAKBUN 	: hakbun,\n");
      out.write("				DEBUG	: \"F\"\n");
      out.write("			};\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			method	: \"post\",\n");
      out.write("			url		: \"checkHakbun.do\",\n");
      out.write("			data	: param,\n");
      out.write("			dataType : \"JSON\",\n");
      out.write("			async : true, \n");
      out.write("			beforeSend : beforeAjax,\n");
      out.write("			success : successCheckHakbun,\n");
      out.write("			error : errCheckHakbun\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function beforeAjax(xmlHttpRequest) {\n");
      out.write("	xmlHttpRequest.setRequestHeader(\"AJAX\", \"true\");\n");
      out.write("}\n");
      out.write("function errCheckHakbun(xhr,status,error) {\n");
      out.write("\n");
      out.write("	if(xhr.status == 999) {\n");
      out.write("		alert(\"세션이 종료되었습니다.\");\n");
      out.write("	} else {\n");
      out.write("		alert(\"조회중 에러가 발생하였습니다.\");\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function successCheckHakbun(result) {\n");
      out.write("	var data = result.returnData.resultData_hakbun[0];\n");
      out.write("	$(\"#alertDiv\").hide();\n");
      out.write("	if(typeof data!=\"undefined\"){\n");
      out.write("		console.log(\"학번-->\"+data.HAKBUN+\" 이름-->\"+data.NAME);\n");
      out.write("		loginUser = data.NAME;\n");
      out.write("		var inHtml = '<div class=\"alert alert-success\" style=\\'text-align:center\\'>' +\n");
      out.write("				      '<span class=\"closebtn\" onclick=\"this.parentElement.style.display=\\'none\\';\">&times;</span>' +\n");
      out.write("				      '<strong>반갑습니다 ' + data.NAME + ' 학생   </strong>' +\n");
      out.write("				      '<span id=\"demo\"></span></div>';\n");
      out.write("		$(\"#changeArea\").html(inHtml);\n");
      out.write("		var countDownDate = new Date(\"Jan 5, 2024 15:37:24\").getTime();\n");
      out.write("		var now = new Date(\"Jan 5, 2024 15:37:22\").getTime();\n");
      out.write("		var distance = countDownDate - now;\n");
      out.write("		var seconds = Math.floor((distance % (1000 * 60)) / 1000);\n");
      out.write("		var x = setInterval(function() {				\n");
      out.write("			document.getElementById(\"demo\").innerHTML = seconds + \"초 \";\n");
      out.write("			seconds -= 1;\n");
      out.write("			if (seconds < 0) {\n");
      out.write("				clearInterval(x);\n");
      out.write("				document.getElementById(\"demo\").innerHTML = \"인증완료\";\n");
      out.write("			}\n");
      out.write("		}, 1000);\n");
      out.write("		setTimeout(function() {\n");
      out.write("			$(\"#id01\").hide();\n");
      out.write("			$(\"#clearBoard\").html(\"\");\n");
      out.write("			step1();\n");
      out.write("		}, 3000);\n");
      out.write("	}else{\n");
      out.write("		$(\"#alertDiv\").show();		\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("var item='';\n");
      out.write("\n");
      out.write("function logging(value){	\n");
      out.write("	var studentNm = loginUser;\n");
      out.write("	var srcFlag = true;\n");
      out.write("	item = value;\n");
      out.write("	if(studentNm !=\"\" && item !=\"\") {\n");
      out.write("		console.log(\"item-->\"+item+\" 이름-->\"+studentNm);	\n");
      out.write("	\n");
      out.write("	}else{\n");
      out.write("		srcFlag = false;\n");
      out.write("	}\n");
      out.write("		\n");
      out.write("	if(srcFlag){	\n");
      out.write("		param = { studentNm : studentNm, item : item };		\n");
      out.write("		$.ajax({\n");
      out.write("			method	: \"post\",\n");
      out.write("			url		: \"logging.do\",\n");
      out.write("			data	: param,\n");
      out.write("			dataType : \"JSON\",\n");
      out.write("			async : true, \n");
      out.write("			beforeSend : beforeAjax,\n");
      out.write("			success : successLogging,\n");
      out.write("			error : errLoggingAdd\n");
      out.write("		});\n");
      out.write("		\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("function errLoggingAdd(xhr,status,error) {\n");
      out.write("\n");
      out.write("	if(xhr.status == 999) {\n");
      out.write("		alert(\"세션이 종료되었습니다.\");\n");
      out.write("	} else {\n");
      out.write("		alert(\"로그 생성중 에러가 발생하였습니다.\");\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("function successLogging(result) {\n");
      out.write("	var data = result.returnData;\n");
      out.write("	alert(\"[\"+data+\"] 로그 생성완료\")\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function step1(){\n");
      out.write("	var inHtml = '';\n");
      out.write("	var inHtml = \n");
      out.write("	    '<nav class=\"w3-sidebar w3-bar-block w3-white w3-collapse w3-top\" style=\"z-index:3;width:250px\" id=\"mySidebar\">' +\n");
      out.write("	    '<div class=\"w3-container w3-display-container w3-padding-16\">' +\n");
      out.write("	    '<i onclick=\"w3_close()\" class=\"fa fa-remove w3-hide-large w3-button w3-display-topright\"></i>' +\n");
      out.write("	    '<h3 class=\"w3-wide\"><a href=\"/\"><b>컴퓨터네트워크</b></a></h3>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<div class=\"w3-padding-64 w3-large w3-text-grey\" style=\"font-weight:bold\">' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Shirts 클릭\\');\">Shirts</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Dresses 클릭\\');\">Dresses</a>' +\n");
      out.write("	    '<a onclick=\"myAccFunc()\" href=\"javascript:void(0)\" class=\"w3-button w3-block w3-white w3-left-align\" id=\"myBtn\">' +\n");
      out.write("	    'Jeans <i class=\"fa fa-caret-down\"></i>' +\n");
      out.write("	    '</a>' +\n");
      out.write("	    '<div id=\"demoAcc\" class=\"w3-bar-block w3-hide w3-padding-large w3-medium\">' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button w3-light-grey\" onclick=\"logging(\\'Skinny 클릭\\');\"><i class=\"fa fa-caret-right w3-margin-right\"></i>Skinny</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Relaxed 클릭\\');\">Relaxed</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Bootcut 클릭\\');\">Bootcut</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Straight 클릭\\');\">Straight</a>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Jackets 클릭\\');\">Jackets</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Gymwear 클릭\\');\">Gymwear</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Blazers 클릭\\');\">Blazers</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button\" onclick=\"logging(\\'Shoes 클릭\\');\">Shoes</a>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<a href=\"#footer\" class=\"w3-bar-item w3-button w3-padding\" onclick=\"logging(\\'Contact 클릭\\');\">Contact</a>' +\n");
      out.write("	    //'<a href=\"javascript:void(0)\" class=\"w3-bar-item w3-button w3-padding\" onclick=\"document.getElementById(\\'newsletter\\').style.display=\\'block\\'\">Newsletter</a>' +\n");
      out.write("	    '<a href=\"#\" class=\"w3-bar-item w3-button w3-padding\" onclick=\"logging(\\'Newsletter 클릭\\');\">Newsletter</a>' +\n");
      out.write("	    '<a href=\"#footer\" class=\"w3-bar-item w3-button w3-padding\" onclick=\"logging(\\'Subscribe 클릭\\');\">Subscribe</a>' +\n");
      out.write("	    '</nav>' +\n");
      out.write("\n");
      out.write("	    // Top menu on small screens\n");
      out.write("	    '<header class=\"w3-bar w3-top w3-hide-large w3-black w3-xlarge\">' +\n");
      out.write("	    '<div class=\"w3-bar-item w3-padding-24 w3-wide\">LOGO</div>' +\n");
      out.write("	    '<a href=\"javascript:void(0)\" class=\"w3-bar-item w3-button w3-padding-24 w3-right\" onclick=\"w3_open()\"><i class=\"fa fa-bars\"></i></a>' +\n");
      out.write("	    '</header>' +\n");
      out.write("\n");
      out.write("	    // Overlay effect when opening sidebar on small screens\n");
      out.write("	    '<div class=\"w3-overlay w3-hide-large\" onclick=\"w3_close()\" style=\"cursor:pointer\" title=\"close side menu\" id=\"myOverlay\"></div>' +\n");
      out.write("\n");
      out.write("	    // !PAGE CONTENT!\n");
      out.write("	    '<div class=\"w3-main\" style=\"margin-left:250px\">' +\n");
      out.write("\n");
      out.write("	    // Push down content on small screens\n");
      out.write("	    '<div class=\"w3-hide-large\" style=\"margin-top:83px\"></div>' +\n");
      out.write("\n");
      out.write("	    // Top header\n");
      out.write("	    '<header class=\"w3-container w3-xlarge\">' +\n");
      out.write("	    '<p class=\"w3-left\">Jeans</p>' +\n");
      out.write("	    '<p class=\"w3-right\">' +\n");
      out.write("	    '<i class=\"fa fa-shopping-cart w3-margin-right\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-search\"></i>' +\n");
      out.write("	    '</p>' +\n");
      out.write("	    '</header>' +\n");
      out.write("\n");
      out.write("	    // Image header\n");
      out.write("	    '<div class=\"w3-display-container w3-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans.jpg\" alt=\"Jeans\" style=\"width:100%\">' +\n");
      out.write("	    '<div class=\"w3-display-topleft w3-text-white\" style=\"padding:24px 48px\">' +\n");
      out.write("	    '<h1 class=\"w3-jumbo w3-hide-small\">New arrivals</h1>' +\n");
      out.write("	    '<h1 class=\"w3-hide-large w3-hide-medium\">New arrivals</h1>' +\n");
      out.write("	    '<h1 class=\"w3-hide-small\">COLLECTION 2023</h1>' +\n");
      out.write("	    '<p><a href=\"#jeans\" class=\"w3-button w3-black w3-padding-large w3-large\" onclick=\"logging(\\'LOGGING NOW 클릭\\');\">LOGGING NOW</a></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-container w3-text-grey\" id=\"jeans\">' +\n");
      out.write("	    '<p>8 items</p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    // Product grid\n");
      out.write("	    '<div class=\"w3-row w3-grayscale\">' +\n");
      out.write("	    '<div class=\"w3-col l3 s6\">' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans1.jpg\" style=\"width:100%\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'무릎만 찢어진 청바지\\');\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>무릎만 찢어진 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans2.jpg\" style=\"width:100%\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'허벅지 찢어진 청바지\\');\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>허벅지 찢어진 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-col l3 s6\">' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans5.jpg\" style=\"width:381px;height:476px;\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">New</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'청반바지(남)\\');\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>청반바지(남)<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans6.jpg\" style=\"width:381px;height:476px;\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">New</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\"  onclick=\"logging(\\'청반바지(여)\\');\" >Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>청반바지(여)<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-col l3 s6\">' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans3.jpg\" style=\"width:100%\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'멀쩡한 청바지\\');\" >Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>멀쩡한 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image//jeans4.jpg\" style=\"width:100%\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\"  onclick=\"logging(\\'빈티지 청바지\\');\" >Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>빈티지 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-col l3 s6\">' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans7.jpg\" style=\"width:381px;height:476px;\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'무릎 많이 찢어진 청바지\\');\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>무릎 많이 찢어진 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<div class=\"w3-container\">' +\n");
      out.write("	    '<div class=\"w3-display-container\">' +\n");
      out.write("	    '<img src=\"../resources/image/jeans8.jpg\" style=\"width:381px;height:476px;\">' +\n");
      out.write("	    '<span class=\"w3-tag w3-display-topleft\">Sale</span>' +\n");
      out.write("	    '<div class=\"w3-display-middle w3-display-hover\">' +\n");
      out.write("	    '<button class=\"w3-button w3-black\" onclick=\"logging(\\'군데 군데 찢어진 청바지\\');\">Buy now <i class=\"fa fa-shopping-cart\"></i></button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '<p>군데 군데 찢어진 청바지<br></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    // Subscribe section\n");
      out.write("	    '<div class=\"w3-container w3-black w3-padding-32\">' +\n");
      out.write("	    '<h1>Subscribe</h1>' +\n");
      out.write("	    '<p>To get special offers and VIP treatment:</p>' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Enter e-mail\" style=\"width:100%\"></p>' +\n");
      out.write("	    '<button type=\"button\" class=\"w3-button w3-red w3-margin-bottom\">Subscribe</button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    // Footer\n");
      out.write("	    '<footer class=\"w3-padding-64 w3-light-grey w3-small w3-center\" id=\"footer\">' +\n");
      out.write("	    '<div class=\"w3-row-padding\">' +\n");
      out.write("	    '<div class=\"w3-col s4\">' +\n");
      out.write("	    '<h4>Contact</h4>' +\n");
      out.write("	    '<p>Questions? Go ahead.</p>' +\n");
      out.write("	    '<form action=\"/action_page.php\" target=\"_blank\">' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Name\" name=\"Name\" id=\"txtName\"></p>' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Email\" name=\"Email\" id=\"txtMail\"></p>' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Subject\" name=\"Subject\" id=\"txtSub\"></p>' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Message\" name=\"Message\" id=\"txtMsg\"></p>' +\n");
      out.write("	    '<button class=\"w3-button w3-block w3-black\" onclick=\"logging(\\'Send 클릭\\');\">Send</button>' +\n");
      out.write("	    '</form>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-col s4\">' +\n");
      out.write("	    '<h4>About</h4>' +\n");
      out.write("	    '<p><a href=\"#\">About us</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">We\\'re hiring</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Support</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Find store</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Shipment</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Payment</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Gift card</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Return</a></p>' +\n");
      out.write("	    '<p><a href=\"#\">Help</a></p>' +\n");
      out.write("	    '</div>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-col s4 w3-justify\">' +\n");
      out.write("	    '<h4>Store</h4>' +\n");
      out.write("	    '<p><i class=\"fa fa-fw fa-map-marker\"></i> 컴퓨터네트워크</p>' +\n");
      out.write("	    '<p><i class=\"fa fa-fw fa-phone\"></i> +8242-821-6879</p>' +\n");
      out.write("	    '<p><i class=\"fa fa-fw fa-envelope\"></i> lbhzzang@o.cnu.ac.kr</p>' +\n");
      out.write("	    '<h4>We accept</h4>' +\n");
      out.write("	    '<p><i class=\"fa fa-fw fa-cc-amex\"></i> Amex</p>' +\n");
      out.write("	    '<p><i class=\"fa fa-fw fa-credit-card\"></i> Credit Card</p>' +\n");
      out.write("	    '<br>' +\n");
      out.write("	    '<i class=\"fa fa-facebook-official w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-instagram w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-snapchat w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-pinterest-p w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-twitter w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '<i class=\"fa fa-linkedin w3-hover-opacity w3-large\"></i>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</footer>' +\n");
      out.write("\n");
      out.write("	    '<div class=\"w3-black w3-center w3-padding-24\">Powered by <a href=\"https://sites.google.com/view/monetcnu\" title=\"CNU\" target=\"_blank\" class=\"w3-hover-opacity\"CNU</a></div>' +\n");
      out.write("\n");
      out.write("	    // Newsletter Modal\n");
      out.write("	    '<div id=\"newsletter\" class=\"w3-modal\">' +\n");
      out.write("	    '<div class=\"w3-modal-content w3-animate-zoom\" style=\"padding:32px\">' +\n");
      out.write("	    '<div class=\"w3-container w3-white w3-center\">' +\n");
      out.write("	    '<i onclick=\"document.getElementById(\\'newsletter\\').style.display=\\'none\\'\" class=\"fa fa-remove w3-right w3-button w3-transparent w3-xxlarge\"></i>' +\n");
      out.write("	    '<h2 class=\"w3-wide\">NEWSLETTER</h2>' +\n");
      out.write("	    '<p>Join our mailing list to receive updates on new arrivals and special offers.</p>' +\n");
      out.write("	    '<p><input class=\"w3-input w3-border\" type=\"text\" placeholder=\"Enter e-mail\"></p>' +\n");
      out.write("	    '<button type=\"button\" class=\"w3-button w3-padding-large w3-red w3-margin-bottom\" onclick=\"document.getElementById(\\'newsletter\\').style.display=\\'none\\'\">Subscribe</button>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>' +\n");
      out.write("	    '</div>';\n");
      out.write("\n");
      out.write("	$(\"#clearBoard\").html(inHtml);\n");
      out.write("	// Click on the \"Jeans\" link on page load to open the accordion for demo purposes\n");
      out.write("	document.getElementById(\"myBtn\").click();\n");
      out.write("	/*\n");
      out.write("	$( document ).ready( function() {	\n");
      out.write("	    $(\"#itemBtn\").click(function(){\n");
      out.write("	       console.log($(this).attr('value'));\n");
      out.write("	       item = $(this).attr('value');\n");
      out.write("	    });\n");
      out.write("\n");
      out.write("	});\n");
      out.write("	*/\n");
      out.write("}\n");
      out.write("\n");
      out.write("//Accordion \n");
      out.write("function myAccFunc() {\n");
      out.write("  var x = document.getElementById(\"demoAcc\");\n");
      out.write("  if (x.className.indexOf(\"w3-show\") == -1) {\n");
      out.write("    x.className += \" w3-show\";\n");
      out.write("  } else {\n");
      out.write("    x.className = x.className.replace(\" w3-show\", \"\");\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write("// Open and close sidebar\n");
      out.write("function w3_open() {\n");
      out.write("  document.getElementById(\"mySidebar\").style.display = \"block\";\n");
      out.write("  document.getElementById(\"myOverlay\").style.display = \"block\";\n");
      out.write("}\n");
      out.write(" \n");
      out.write("function w3_close() {\n");
      out.write("  document.getElementById(\"mySidebar\").style.display = \"none\";\n");
      out.write("  document.getElementById(\"myOverlay\").style.display = \"none\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("var modal = document.getElementById('id01');\n");
      out.write("//When the user clicks anywhere outside of the modal, close it\n");
      out.write("window.onclick = function(event) {\n");
      out.write(" if (event.target == modal) {\n");
      out.write("     modal.style.display = \"none\";\n");
      out.write(" }\n");
      out.write("}\n");
      out.write("$(function(){\n");
      out.write("	$(\"#hakbun\").keypress(function(e){\n");
      out.write("		if(e.keyCode && e.keyCode == 13){\n");
      out.write("			 //e.preventDefault();\n");
      out.write("			 login();\n");
      out.write("	    }\n");
      out.write("	});\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"clearBoard\">\n");
      out.write("<div><h2>Logging 실습</h2></div>\n");
      out.write("<div><button onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;margin-left: 50px;\">접속하기</button></div>\n");
      out.write("\n");
      out.write("<div class=\"modal\" id=\"id01\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("\n");
      out.write("      <!-- Modal Header -->\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <span onclick=\"document.getElementById('id01').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\n");
      out.write("        <img src=\"../resources/image/cnu_logo.png\" alt=\"CNU\" class=\"avatar\" style=\"margin-left: 120px;\">\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <!-- Modal body -->\n");
      out.write("      <div class=\"modal-body\" style=\"height:290px;\" id=\"changeArea\">\n");
      out.write("		<label for=\"hakbun\"><b>학번</b></label>      \n");
      out.write("	    <input type=\"text\" id=\"hakbun\" placeholder=\"자신의 학번을 입력하세요\" name=\"hakbun\" maxlength=\"9\">        \n");
      out.write("	    <a href=\"#\" onclick=\"login()\" class=\"btn-sch\" id=\"btn_srch\">로그인</a>\n");
      out.write("	    <div id =\"alertDiv\" class=\"alert\" style=\"display:none;\">\n");
      out.write("			<span class=\"closebtn\" onclick=\"this.parentElement.style.display='none';\">&times;</span> \n");
      out.write("			<strong style=\"color: red;\">정확한 학번</strong>을 입력해 주세요.\n");
      out.write("	    </div>   \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
